# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_auto_20160930_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=16, unique=True, verbose_name='用户名')),
                ('username', models.CharField(default='.', max_length=16, verbose_name='姓名')),
                ('password', models.CharField(default='.', max_length=16, verbose_name='密码')),
                ('mailbox', models.EmailField(max_length=99, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=16, unique=True, verbose_name='用户名')),
                ('username', models.CharField(default='.', max_length=16, verbose_name='姓名')),
                ('password', models.CharField(default='.', max_length=16, verbose_name='密码')),
                ('mailbox', models.EmailField(max_length=99, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '老师',
                'verbose_name_plural': '老师',
            },
        ),
        migrations.DeleteModel(
            name='Labstudent',
        ),
        migrations.DeleteModel(
            name='Labteacher',
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Teacher'),
        ),
    ]
