# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_auto_20161001_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(default='.', max_length=16, verbose_name='組別'),
        ),
    ]
