# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_auto_20161001_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='group',
            new_name='groupname',
        ),
    ]
