# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_student_teamname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Teacher', verbose_name='老師'),
        ),
    ]
