# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_auto_20161001_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f01', models.CharField(default='.', max_length=99, verbose_name='标题')),
                ('f02', models.DateTimeField(default='.', max_length=99, verbose_name='时间')),
                ('f03', models.TextField(default='.', verbose_name='内容')),
            ],
            options={
                'verbose_name_plural': '信息',
                'verbose_name': '信息',
            },
        ),
        migrations.DeleteModel(
            name='Labinfo',
        ),
    ]
