# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0014_auto_20161001_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='f02',
            field=models.DateTimeField(verbose_name='时间'),
        ),
    ]
