# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0015_auto_20161001_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupid', models.CharField(default='.', max_length=16, unique=True, verbose_name='組別')),
                ('groupname', models.CharField(default='.', max_length=16, verbose_name='組別')),
            ],
            options={
                'verbose_name': '組別',
                'verbose_name_plural': '組別',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='mailbox',
            field=models.EmailField(max_length=99, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mailbox',
            field=models.EmailField(max_length=99, unique=True, verbose_name='邮箱'),
        ),
    ]
