# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0018_remove_student_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.IntegerField(default=1, verbose_name='組別'),
        ),
    ]
