# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0019_student_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamid', models.CharField(default='.', max_length=16, unique=True, verbose_name='組別編號')),
                ('teamname', models.CharField(default='.', max_length=16, verbose_name='組別名稱')),
            ],
            options={
                'verbose_name_plural': '組別',
                'verbose_name': '組別',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Team', verbose_name='組別xx'),
        ),
    ]
