# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0023_auto_20161001_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupname',
            field=models.CharField(default='.', max_length=16, unique=True, verbose_name='組別名稱'),
        ),
    ]
