# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0024_auto_20161001_2346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AlterField(
            model_name='team',
            name='teamname',
            field=models.CharField(default='.', max_length=16, unique=True, verbose_name='組別名稱'),
        ),
    ]
