# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0026_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentid',
            field=models.CharField(default='.', max_length=16, verbose_name='学号'),
        ),
    ]
