# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0028_experiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rqsttime', models.DateField(auto_now_add=True, verbose_name='申请时间')),
                ('expstart', models.DateTimeField(verbose_name='start时间')),
                ('expend', models.DateTimeField(verbose_name='end时间')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Experiment', verbose_name='实验项目')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Teacher', verbose_name='老師')),
            ],
            options={
                'verbose_name': '实验项目',
                'verbose_name_plural': '实验项目',
            },
        ),
    ]
