# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0031_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='team',
            field=models.IntegerField(default=1, verbose_name='组别'),
        ),
    ]
