# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0032_request_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Teacher', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='request',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Team', verbose_name='组别'),
        ),
    ]
