# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0033_auto_20161002_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=-1, verbose_name='分数')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Request', verbose_name='实验申请信息')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Student', verbose_name='用户名')),
            ],
            options={
                'verbose_name': '学生实验课程',
                'verbose_name_plural': '学生实验课程',
            },
        ),
    ]
