# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0037_auto_20161002_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='score',
        ),
    ]
