# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0038_remove_action_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='request',
        ),
        migrations.RemoveField(
            model_name='action',
            name='student',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
