# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0040_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='score',
            field=models.IntegerField(null=True, verbose_name='分数'),
        ),
    ]
