# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0042_auto_20161002_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='apvd1',
            field=models.CharField(choices=[('未审核', '未审核'), ('已审核', '已审核')], default='未审核', max_length=99, verbose_name='审核1'),
        ),
        migrations.AddField(
            model_name='action',
            name='apvd2',
            field=models.CharField(choices=[('未审核', '未审核'), ('已审核', '已审核')], default='未审核', max_length=99, verbose_name='审核2'),
        ),
    ]
