# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0043_auto_20161002_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='apvd1',
        ),
        migrations.RemoveField(
            model_name='action',
            name='apvd2',
        ),
        migrations.AddField(
            model_name='request',
            name='remarks',
            field=models.CharField(default='.', max_length=250, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('申请', '申请'), ('审核', '审核'), ('实施', '实施'), ('完成', '完成')], default='申请', max_length=16, verbose_name='申请状态'),
        ),
    ]
