# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0046_request2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request2',
            name='status',
            field=models.CharField(choices=[('申请', '申请'), ('指导老师核可', '指导老师核可'), ('核准', '核准'), ('审核', '审核'), ('实施', '实施'), ('完成', '完成')], default='申请', max_length=16, verbose_name='申请状态'),
        ),
    ]
