# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0048_auto_20161002_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='requestby',
            field=models.CharField(choices=[('老师', '老师'), ('学生', '学生')], default='老师', max_length=16, verbose_name='申请類型'),
        ),
    ]
