# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0049_action_requestby'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hwnote', models.CharField(default='.', max_length=99, unique=True, verbose_name='硬件序列号')),
            ],
            options={
                'verbose_name_plural': '授权设备',
                'verbose_name': '授权设备',
            },
        ),
        migrations.CreateModel(
            name='CurrentDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hwnote', models.CharField(default='.', max_length=99, unique=True, verbose_name='硬件序列号')),
            ],
            options={
                'verbose_name_plural': '当前设备',
                'verbose_name': '当前设备',
            },
        ),
    ]
