# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0051_auto_20161002_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dido', models.CharField(choices=[('DI', 'DI'), ('DO', 'DO')], default='DI', max_length=16, verbose_name='类型')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Equipment', verbose_name='设备名称')),
            ],
            options={
                'verbose_name_plural': '板卡信息',
                'verbose_name': '板卡信息',
            },
        ),
    ]
