# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0052_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='addr',
            field=models.CharField(default='.', max_length=96, verbose_name='变量地址'),
        ),
        migrations.AddField(
            model_name='board',
            name='var1',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0, verbose_name='变量值'),
        ),
        migrations.AddField(
            model_name='board',
            name='var2',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0, verbose_name='通讯状态'),
        ),
    ]
